#!/usr/bin/env sh

set -o errexit                  # exit immediately if a command exits
                                # with a non-zero status
set -o nounset                  # treat unset variables as an error
                                # when substituting

BUILDDIR=$(readlink -m ${1:-b})
SOURCEDIR=$(dirname $(readlink -e "$0"))

mkdir -p "$BUILDDIR"
cd "$BUILDDIR"
cmake "$SOURCEDIR"
cmake --build .
ctest
echo "run to (re)build: make -C $BUILDDIR ..."
