#!/usr/bin/env sh

set -o errexit                  # exit immediately if a command exits
                                # with a non-zero status
set -o nounset                  # treat unset variables as an error
                                # when substituting

TOPDIR=$(dirname $(readlink -e "$0"))
PROBLEMNUM=$(printf "%04d" $1)
PROBLEMDIR=$(echo $TOPDIR/$PROBLEMNUM-*)
BUILDDIR=$TOPDIR/tmp/$PROBLEMNUM

if test ! -d "$PROBLEMDIR"; then
    echo "error: problem #$1 is not found" >&2
    exit 1
fi

mkdir -p "$BUILDDIR"
cd "$BUILDDIR"
cmake "$PROBLEMDIR"
cmake --build "$PWD"
ctest --output-on-failure -V
